apiVersion: serving.knative.dev/v1 
kind: Service 
metadata: 
  name: event-display 
  namespace: cnr-fundamentals-w01-s001
spec: 
  template: 
    spec: 
      containers: 
      - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
